# Server port
server.port=8081

# Application name (must match Feign client name)
spring.application.name=book-service

# Postgre Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Register using IP address
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
